### PR TITLE
task

### PR DESCRIPTION
**Pull request by qazaqyanke**
hello from space and IITU
from qazaqyanke at march 2022

### CODE REVIEW

**Comment by sea-kg** [comment]
What is it? Please modify only one file in web

**Comment by qazaqyanke** [comment]
its for a ctfwall

**Comment by sea-kg** [comment]
Ctfwall in this file:
https://github.com/freehackquest/fhq-server/blob/dev/web-user/src/app/pages/ctf-wall/ctf-wall.component.html

only there expected changes

**Comment by sea-kg** [comment]
And please recreate fork for fix conflicts

**Pull request closed without merging**
